### ISSUE TITLE
Building errors

### ISSUE THREAD

**Issue by 1-TB** [anonik9900/Essential-Menu#2]
![Screenshot 2021-08-10 101137](https://user-images.githubusercontent.com/18247749/128892608-21505e77-9c7f-42cb-a684-969d91d4bcb1.png)
What needs to be done?

**Comment by vinzy2** [comment]
you need to install the requirments man ([Requirements]
[ScriptHookV](http://www.dev-c.com/gtav/scripthookv/)
[ScriptHookV.NET](https://it.gta5-mods.com/tools/scripthookv-net)
[NativeUI](http://gtaforums.com/topic/809284-net-nativeui/)
[Microsoft .NET Framework 4.8](https://www.microsoft.com/it-it/download/details.aspx?id=42642))
